# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  APP_NAME: rift

tasks:
  run:
    desc: Run the project
    cmds:
      - go run .

  build:
    desc: Build the project
    cmds:
      - go build

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run

  test:
    desc: Run all tests
    cmds:
      - go test -race ./... {{.CLI_ARGS}} -coverprofile=coverage.txt

  cover:
    desc: Open HTML page for the test coverage
    cmds:
      - go tool cover -html=coverage.txt

  logs:
    desc: Watch logs
    cmds:
      - cmd: tail -f ~/Library/Logs/{{.APP_NAME}}/{{.APP_NAME}}.log
        platforms: [darwin]
      - cmd: tail -f ~/.cache/{{.APP_NAME}}/{{.APP_NAME}}.log
        platforms: [linux]

  demo:generate:
    desc: Generate a new demo GIF
    cmds:
      - vhs demo.tape

  demo:publish:
    desc: Publish the demo GIF
    cmds:
      - vhs publish demo.gif

  demo:
    desc: Generate and publish a new demo GIF
    cmds:
      - task: demo:generate
      - task: demo:publish

